name: CI & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # - name: Run tests
      #   run: |
      #     if [ -f tests/test.py ]; then python -m unittest discover -s tests; fi

  deploy-to-hf:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Full git history if needed for versioning or changelog

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Use whatever version you prefer

      - name: Install Hugging Face Hub client
        run: pip install huggingface_hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ secrets.HF_USERNAME }}
          HF_SPACE_NAME: ${{ secrets.HF_SPACE_NAME }}
        run: |
          echo "Pushing latest code to Hugging Face Space"
          git config --global user.email "anb7243@gmail.com"
          git config --global user.name "Abhinav_Gavireddi"

          # Set up Hugging Face CLI
          huggingface-cli login --token "$HF_TOKEN"

          # Add Hugging Face as remote
          git remote add hf https://huggingface.co/spaces/${HF_USERNAME}/${HF_SPACE_NAME}

          # Push code to the Space repo
          git push hf main

          # Optional: Restart Space via API (defensive move)
          python -c "
          from huggingface_hub import HfApi;
          api = HfApi(token='$HF_TOKEN');
          api.restart_space(repo_id='${HF_USERNAME}/${HF_SPACE_NAME}')
